const STORAGE_KEY='contacts-phase-2';
const form=document.getElementById('contactForm');
const list=document.getElementById('contactList');
const emptyState=document.getElementById('emptyState');
const message=document.getElementById('formMessage');
const loader=document.getElementById('loader');
const editModal=document.getElementById('editModal');
const editForm=document.getElementById('editForm');
const editMessage=document.getElementById('editMessage');
const cancelEdit=document.getElementById('cancelEdit');
let contacts=[];let editingId=null;
const icon=(gender)=>gender==='female'?'👩':'👨';
const save=()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(contacts));
const render=()=>{list.innerHTML='';emptyState.hidden=contacts.length>0;contacts.forEach(c=>{const li=document.createElement('li');li.className='contact-list__item';li.innerHTML=`<span>${icon(c.gender)} ${c.name} ${c.lastname} - ${c.city}</span><div class="contact-list__actions"><button class="contact-list__action" data-action="edit" data-id="${c.id}">✏️</button><button class="contact-list__action" data-action="delete" data-id="${c.id}">🗑️</button></div>`;list.appendChild(li);});};
const load=()=>{loader.classList.remove('loader--hidden');setTimeout(()=>{contacts=JSON.parse(localStorage.getItem(STORAGE_KEY))||[];render();loader.classList.add('loader--hidden');},400)};
const values=(formEl)=>Object.fromEntries(new FormData(formEl));
const validate=(obj)=>['name','lastname','phone','city','address','gender'].every(k=>String(obj[k]||'').trim());
form.addEventListener('submit',e=>{e.preventDefault();const data=values(form);if(!validate(data)){message.textContent='Todos los campos son obligatorios.';return;}contacts.unshift({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),...data});save();render();form.reset();message.textContent='Contacto guardado.';});
list.addEventListener('click',e=>{const btn=e.target.closest('[data-action]');if(!btn)return;const {action,id}=btn.dataset;if(action==='delete'){contacts=contacts.filter(c=>c.id!==id);save();render();}if(action==='edit'){const current=contacts.find(c=>c.id===id);if(!current)return;editingId=id;editForm.name.value=current.name;editForm.lastname.value=current.lastname;editForm.phone.value=current.phone;editForm.city.value=current.city;editForm.address.value=current.address;editForm.querySelector(`input[name="gender"][value="${current.gender}"]`).checked=true;editModal.showModal();}});
editForm.addEventListener('submit',e=>{e.preventDefault();const data=values(editForm);if(!validate(data)){editMessage.textContent='Todos los campos son obligatorios.';return;}contacts=contacts.map(c=>c.id===editingId?{...c,...data}:c);save();render();editModal.close();editForm.reset();});
cancelEdit.addEventListener('click',()=>editModal.close());
load();
